# Generated by Django 4.0 on 2023-11-29 15:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(default='<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n    <title>Product Detail Page</title>\n    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">\n</head>\n<body>\n\n<div class="container mt-5">\n    <div class="row">\n        <div class="col-md-6">\n            <img src="https://via.placeholder.com/400" class="img-fluid" alt="Product Image">\n        </div>\n        <div class="col-md-6">\n            <h2 class="mb-3">Product Name</h2>\n            <p class="text-muted">Category: Electronics</p>\n            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>\n            <p class="font-weight-bold mb-1">Price: $99.99</p>\n            <div class="mb-3">\n                <label for="quantity">Quantity:</label>\n                <input type="number" id="quantity" class="form-control" value="1" min="1">\n            </div>\n            <button class="btn btn-primary">Add to Cart</button>\n        </div>\n    </div>\n\n    <div class="row mt-5">\n        <div class="col-md-12">\n            <h3>Product Details</h3>\n            <ul class="list-group">\n                <li class="list-group-item">Brand: XYZ</li>\n                <li class="list-group-item">Color: Black</li>\n                <li class="list-group-item">Material: Plastic</li>\n                <li class="list-group-item">Features: Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>\n            </ul>\n        </div>\n    </div>\n</div>\n\n<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>\n<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>\n\n</body>\n</html>\n'),
        ),
    ]
