# Generated by Django 4.0 on 2023-12-15 07:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTML_DIY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('html_content', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
