# Generated by Django 4.0 on 2023-12-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_html_diy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_diy',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
