# Generated by Django 4.0 on 2023-12-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_product_images_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='uploads/products/'),
        ),
    ]
