# Generated by Django 4.0 on 2023-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='blog/images/base-cob-led-2.jpg', null=True, upload_to='news_images/'),
        ),
    ]
