# Generated by Django 4.0 on 2023-12-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='blog/images/base-cob-led.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
