# Generated by Django 4.0 on 2023-12-14 07:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_blog_alter_review_movie_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='description_txt',
        ),
        migrations.AddField(
            model_name='blog',
            name='description_html',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
